name: count

on:
  workflow_dispatch:

jobs:
  count:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run
        run: python run.py
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
